name: "Static Analysis"

on: [push]

jobs:
  codeql:
    name: codeql
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        language: ['cpp']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: apt-get install packages
      run: sudo apt-get update -qq &&
           sudo apt-get install --no-install-recommends -y
               bison
               build-essential
               check
               clang
               flex
               git
               gperf
               llvm
               pkg-config

    - name: Get env.sh
      run: |
           mkdir projects
           wget -O projects/env.sh https://raw.githubusercontent.com/netsurf-browser/netsurf/refs/heads/master/docs/env.sh

    - name: Build and install project deps
      env:
        TARGET: ${{ github.event.repository.name }}
      run: |
          export TARGET_WORKSPACE="$(pwd)/projects"
          source projects/env.sh
          ns-clone -d -s
          ns-make-libs install

    # TODO the feature doesn't work as expected, maybe due to a prive repo but
    # not sure.
    # see https://github.com/github/codeql-action/issues/572
    # I (Pierre) continue-on-error for now.

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
      continue-on-error: true

    - name: Build Library
      run: |
          export TARGET_WORKSPACE="$(pwd)/projects"
          source projects/env.sh
          make -j"$(nproc)"
      continue-on-error: true

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      continue-on-error: true
